### ISSUE TITLE
Enable Images in Refinery on test3 

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeBMD2#282]
I'm at the point where I would like to start adding images to the markup Guide. However, images are not yet enabled in Refinery, or so it seems — there is a long list of ?REG images under 'Images', plus a couple that Philip tried to upload, but no visible thumbnails and trying to insert an image fails.

**Comment by Vino-S** [comment]
working on it

**Comment by Vino-S** [comment]
Fixed it but old images need to be re-uploaded.Apologies

**Comment by AlOneill** [comment]
@Vino-S Thank you. No worries re old images as only 2 are needed on BMD — I'll let Philip know.

**Comment by AlOneill** [comment]
@Vino-S Just tried to upload an image — not working. I tried logging out and back in again, but still not working.

I'm still seeing the old listing without the images. Perhaps I was too quick or … ?

**Comment by Vino-S** [comment]
Hi @AlOneill , 
I fixed on test2 but not in test3. My mistake did not mention it.
I had fixed in test3 too. Could you test it once again, please?

**Comment by AlOneill** [comment]
@Vino-S Yes, all now working as expected! Thank you.

Should I now delete all the old images from the listing? Or do you have a way to delete them all in one go?

**Comment by richpomfret** [comment]
@Vino-S to delete images in one go then we can close.

**Comment by PatReynolds** [comment]
@Vino-S will delete in one go and let you know, @AlOneill

**Comment by Vino-S** [comment]
can be closed now

**Comment by AlOneill** [comment]
@vino Many thanks — listing now looking good.
