### ISSUE TITLE
District links go straight to UKBMD and ignore our own District page

### ISSUE THREAD

**Issue by richardofsussex** [FreeUKGen/FreeBMD2#520]
In the search results (and the Entry information view), the District is presented as a hyperlink:
![image.png](https://images.zenhubusercontent.com/5d3970212c1c7b71d87ac39e/b5bb499a-18ee-4c19-b1b9-e6a22fb2d806)

However, this link takes you out to the UKBMD page for the District. Meanwhile, we have a perfectly good page for that District, which itself includes a link out to UKBMD:
![image.png](https://images.zenhubusercontent.com/5d3970212c1c7b71d87ac39e/c3930f34-decf-4cf1-bd63-621eaa4c9f5f)

Surely the first link should go to our own District page: https://test3.freebmd.org.uk/districts/991/details-of-preston-district?locale=en, particularly as it is not that easy to find that page via the Records section of the site?

**Comment by DeniseColbert** [comment]
@richardofsussex ichard to change these links

**Comment by richardofsussex** [comment]
OK, @Vino-S I have pushed the branch fb_520_rbl which should fix these links. As mentioned in the commit, the page fails because an earlier fix (to the data structure) is not [yet] reflected in the BMD development branch.

**Comment by richardofsussex** [comment]
@Vino-S I have changed the links, and they _should_ work in test3. They fail to deliver a page on my local system because of #522 not being resolved.

**Comment by DeniseColbert** [comment]
@Vino-S to address #522 and then deploy the branch to test3 if necessary

**Comment by Vino-S** [comment]
#522 deployed to test3 and beta.
Configuration changes for new District Table update

**Comment by DeniseColbert** [comment]
I tested this, Test 3 search went on for~~ever~~ ages and Beta, district links still go to UKBMD

**Comment by richardofsussex** [comment]
In fact, the links are still pointing to UKBMD in both test3 and beta.  In the fb_520_rbl branch, I have this source in _desktop_freebmd.html.erb:
![image](https://user-images.githubusercontent.com/2197102/214325167-dd793ef1-ddc5-413c-b3e1-ef753b7791b9.png)
(I've just pushed it, but I didn't change this aspect, just fixed the 'extra date range for Districts' issue so it would display.)

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by DeniseColbert** [comment]
Needs adding to Entry Information page also.

**Comment by Vino-S** [comment]
Ready for testing in test2

**Comment by richardofsussex** [comment]
In test2 the link in the search results list page works fine. However attempting to go to the entry details view, to check the link there, gives an error:
![image.png](https://images.zenhubusercontent.com/5d3970212c1c7b71d87ac39e/d9c85789-4c58-4a4a-bd8b-e1e95ef19950)
Meanwhile, in test3 the District is no longer a link in the search results list, and the link from the entry details leads to a (different) error:
![image.png](https://images.zenhubusercontent.com/5d3970212c1c7b71d87ac39e/b26e3f89-97a4-4f2b-8f20-04c9f7f9ea42)

**Comment by DeniseColbert** [comment]
Should be fixed, can now test on Test 2

**Comment by richardofsussex** [comment]
Now fixed on test2

**Comment by richardofsussex** [comment]
Just checked on beta, and it looks fine there. Test2 is also fine. For some reason, the text displayed by test3 is wildly out of date, and it still shows the red "something went wrong" error message when you try to follow the link.

**Comment by richardofsussex** [comment]
Test2 and beta still both fine. Test3 now displays Districts, but _not_ as a link.

**Comment by richardofsussex** [comment]
The links are once again present in the current source code, but they were links to the wrong District! When you follow the link, it throws an error trying to display the County name(s) for the District. I have fixed both issues and pushed my branch for @Vino-S to take to test3.

**Comment by richardofsussex** [comment]
The links now work, when they are present. However, some Districts are presented as plain text, not a link. This is because I found that the DistrictNumber field in the search records often contained the wrong number, causing the link to be to a different District entirely. I used the DistrictName field instead to locate the District record, but this sometimes fails, leading to no link.

I think there is a data consistency issue here, which needs to be addressed.

**Comment by richardofsussex** [comment]
Following an examination of the SQL database which underpins the test3 site, I am confident that there isn't a problem with the data, so long as we handle it in an appropriate manner. As @Vino-S was patiently trying to explain to me, the District[Name] field in the main BestGuess table contains the Type What You See version of the district, as read by the transcriber from the source scan. If you look across the whole set of data, this varies wildly. Whereas the DistrictNumber is carefully curated.

So we need to rely on the DistrictNumber, and use it to look up the correct/standard District name from the Districts table. At present, one of the links does this, and the other one doesn't!

This does raise the question of whether we should be displaying the District as recorded in the source anywhere.

**Comment by richardofsussex** [comment]
Here is a taste of the ways people have recorded/transcribed Bury St Edmunds:

![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/f06afb12-cbc5-456b-b3b3-56aafd7bb37d)

From line 57 we can see that the record marked as 'Bury' in my tests was likely to be Bury St Edmunds. Certainly the one Bury/946 record I checked out had a volume number associated with the town in Suffolk, not the one in Lancashire.

**Comment by KristinaGadzhieva** [comment]
to check on beta
